server:
  port: 8090
# DataSource Config
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  shardingsphere:
    datasource:
      ds:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dddaka?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        initialSize: 10
        minIdle: 2
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
      names: ds
    rules:
      sharding:
        sharding-algorithms:
          custom-table-inline:
            props:
              algorithm-expression: clock_in$->{id % 3}
            type: INLINE
        tables:
          clock_in:
            actual-data-nodes: ds.clock_in$->{0..2}
            table-strategy:
              standard:
                sharding-algorithm-name: custom-table-inline
                sharding-column: id

  #  shardingsphere:
#    datasource:
#      props:
#        sql:
#          show: true
#      names: dddaka
#      dddaka:
#        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:mysql://127.0.0.1/dddaka?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
#        driver-class-name: com.mysql.jdbc.Driver
#        username: root
#        password: 123456
#        initialSize: 10
#        minIdle: 2
#        maxActive: 20
#        maxWait: 60000
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1 FROM DUAL
#    sharding:
#      tables:
#        clock_in:
#          actual-data-nodes: dddaka.clock_in$->{0..2}
#          key-generator:
#            type: SNOWFLAKE
#            column: id
#          table-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: dddaka.clock_in$->{id % 3}

  #------------------------

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1/ddDaka?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initialSize: 10
#      minIdle: 2
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
  redis:
      database: 0
      host: 127.0.0.1
      port: 6380
      password:
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 1000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: ID_WORKER

      field-strategy: NOT_EMPTY
      #
      db-type: MYSQL
  configuration:
    #
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


